### ISSUE TITLE
TFS & VSTS Integration for AS3

### ISSUE THREAD

**Issue by Yliche** [npearce/n8-BigStats#19]
This is probably the wrong repo for this but couldn't find one for this.

There's github integration for the AS3 worker role but for enterprises, I think that TFS and VSTS integration is required for this functionality.

**Comment by npearce** [comment]
Hey, thanks for reaching out. Can you help me out and post this in: https://github.com/npearce/n8-GHE_IaC_WebHook

Thanks,
Nathan
