### ISSUE TITLE
Error retrieving vipResrouceStats: TypeError: Cannot read property 'nestedStats' of undefined

### ISSUE THREAD

**Issue by kvanderp** [npearce/n8-BigStats#64]
Hi,

I'm trying this on a v14.0 BIG-IP. Downloaded latest Bigstats (0.4.1 build 0008) and Appsvcs (3.4.0 build 2). Also tried with Bigstats 0.4.0.

Sent the following config with Postman:

{
    "config": {
        "destination": {
          "protocol": "statsd",
          "address": "192.168.2.247",
          "port": "8125"
        },
        "size": "small",
        "interval": "10",
        "enabled": true,
        "debug": false
      }
}

No packets arrive at Graphite DB.

Restnoded log on BIG-IP:

Mon, 17 Sep 2018 13:06:59 GMT - info: [BigStats - ERROR] - getVipStats() - Error retrieving vipResrouceStats: TypeError: Cannot read property 'nestedStats' of undefined
Mon, 17 Sep 2018 13:06:59 GMT - info: [BigStats - ERROR] - buildSmallStatsObject(): {}
Mon, 17 Sep 2018 13:06:59 GMT - info: [BigStats - ERROR] - pullStats() - Promise Chain Error: TypeError: Cannot read property 'nestedStats' of undefined
Mon, 17 Sep 2018 13:06:59 GMT - info: [BigStats - ERROR] - getVipStats() - Error retrieving vipResrouceStats: TypeError: Cannot read property 'nestedStats' of undefined
Mon, 17 Sep 2018 13:06:59 GMT - info: [BigStats - ERROR] - buildSmallStatsObject(): {}
Mon, 17 Sep 2018 13:06:59 GMT - info: [BigStats - ERROR] - getVipStats() - Error retrieving vipResrouceStats: TypeError: Cannot read property 'nestedStats' of undefined
Mon, 17 Sep 2018 13:06:59 GMT - info: [BigStats - ERROR] - buildSmallStatsObject(): {}
Mon, 17 Sep 2018 13:06:59 GMT - info: [BigStats - ERROR] - getVipStats() - Error retrieving vipResrouceStats: TypeError: Cannot read property 'nestedStats' of undefined
Mon, 17 Sep 2018 13:06:59 GMT - info: [BigStats - ERROR] - buildSmallStatsObject(): {}
Mon, 17 Sep 2018 13:06:59 GMT - info: [BigStats - ERROR] - getVipStats() - Error retrieving vipResrouceStats: TypeError: Cannot read property 'nestedStats' of undefined
Mon, 17 Sep 2018 13:06:59 GMT - info: [BigStats - ERROR] - buildSmallStatsObject(): {}
Mon, 17 Sep 2018 13:06:59 GMT - info: [BigStats - ERROR] - getVipStats() - Error retrieving vipResrouceStats: TypeError: Cannot read property 'nestedStats' of undefined
Mon, 17 Sep 2018 13:06:59 GMT - info: [BigStats - ERROR] - buildSmallStatsObject(): {}
Mon, 17 Sep 2018 13:06:59 GMT - info: [BigStats - ERROR] - getVipStats() - Error retrieving vipResrouceStats: TypeError: Cannot read property 'nestedStats' of undefined
Mon, 17 Sep 2018 13:06:59 GMT - info: [BigStats - ERROR] - buildSmallStatsObject(): {}

Any clues?

Thx,

Koen

**Comment by npearce** [comment]
Hi Koen, launching my first v14 BIG-IP right now... I hadn't noticed it was added to AWS marketplace. Will take a look in just a moment.

Also, did you know that BigStats no longer requires AS3? It still works with AS3 fine, just wanted to make sure you knew it was no longer a requirement.

**Comment by npearce** [comment]
Koen,

I've found the problem. Small change in stats structure in v14. Look out for BigStats v0.4.2 this week! Or just watch for this Issue being closed.

Nathan

**Comment by kvanderp** [comment]
Great, I’ll try it ASAP. Thanks for fixing this. I’m planning on doing a demo on this next week.

Verstuurd vanaf mijn iPhone

Op 17 sep. 2018 om 18:41 heeft Nathan Pearce <notifications@github.com<mailto:notifications@github.com>> het volgende geschreven:


EXTERNAL MAIL: bounces+848413-3c35-k.vanderpoorten=f5.com@sgmail.github.com<mailto:bounces+848413-3c35-k.vanderpoorten=f5.com@sgmail.github.com>


Koen,

I've found the problem. Small change in stats structure in v14. Look out for BigStats v0.4.2 this week! Or just watch for this Issue being closed.

Nathan

**Comment by npearce** [comment]
Try `BigStats-0.4.1-0009.noarch.rpm`. I've tested this on both v13 and v14.

**Comment by kvanderp** [comment]
works like a charm, thx!

**Comment by npearce** [comment]
I'd be really interested in hearing your feedback: https://join.slack.com/t/bigstats/shared_invite/enQtNDM4MDc0NDIwNjQyLTY4YWU2OGViZjRjNTJhY2I2NjUwYWQwNmY2ZjY5NmFjNzJkMjBhMWM1ODIwMzcxMjE4OWQxZDdhOTM1NmFmNjU
