### ISSUE TITLE
Installed packages list returns empty

### ISSUE THREAD

**Issue by vishwanathj** [npearce/n8-BigStats#83]
I installed a single BIG IP instance via heat stack,

I logged into the instance using the root/default credentials.

Next, i followed the instructions at https://github.com/f5devcentral/BigStats/blob/v0.4.1-release/README.md to continue further.

I scp'ed the BigStats-0.4.1-0009.noarch.rpm to the /var/config/rest/downloads/ directory on the BIG IP instance.

From the shell of the BIG IP instance, I executed the below command
curl -u root:default -X POST http://localhost:8100/mgmt/shared/iapp/package-management-tasks -d '{ "operation":"INSTALL","packageFilePath": "/var/config/rest/downloads/BigStats-0.4.1-0009.noarch.rpm"}' 

I get the below response for the above command 
{"packageFilePath":"/var/config/rest/downloads/BigStats-0.4.1-0009.noarch.rpm","operation":"INSTALL","id":"66968651-2791-4e3d-9a7c-282981c36e1e","status":"CREATED","userReference":{"link":"https://localhost/mgmt/shared/authz/users/root"},"identityReferences":[{"link":"https://localhost/mgmt/shared/authz/users/root"}],"ownerMachineId":"85187f0d-a0b8-4beb-86d5-cbccf9490a48","generation":1,"lastUpdateMicros":1541521219983235,"kind":"shared:iapp:package-management-tasks:iapppackagemanagementtaskstate","selfLink":"https://localhost/mgmt/shared/iapp/package-management-tasks/66968651-2791-4e3d-9a7c-282981c36e1e"}

Next, I try to get the list of installed packages/versions using
curl -u root:default -X GET http://localhost:8100/mgmt/shared/iapp/global-installed-packages

I get the below response that tells me nothing has been installed
{"items":[],"generation":0,"kind":"shared:iapp:global-installed-packages:installedpackagecollectionstate","lastUpdateMicros":0,"selfLink":"https://localhost/mgmt/shared/iapp/global-installed-packages"}

I also tried to use the "id" value to check the installation results using the below command
curl -u root:default -X GET http://localhost:8100/mgmt/shared/iapp/package-management-tasks/66968651-2791-4e3d-9a7c-282981c36e1e

I got the below result which indicates a failure
{"packageFilePath":"/var/config/rest/downloads/BigStats-0.4.1-0009.noarch.rpm","operation":"INSTALL","id":"66968651-2791-4e3d-9a7c-282981c36e1e","status":"FAILED","startTime":"2018-11-06T08:20:20.017-0800","endTime":"2018-11-06T08:20:20.408-0800","errorMessage":"Failed to analyze /var/config/rest/downloads/BigStats-0.4.1-0009.noarch.rpm - java.lang.Exception: Failed to read /var/config/rest/downloads/BigStats-0.4.1-0009.noarch.rpm","userReference":{"link":"https://localhost/mgmt/shared/authz/users/root"},"identityReferences":[{"link":"https://localhost/mgmt/shared/authz/users/root"}],"ownerMachineId":"85187f0d-a0b8-4beb-86d5-cbccf9490a48","generation":3,"lastUpdateMicros":1541521220407926,"kind":"shared:iapp:package-management-tasks:iapppackagemanagementtaskstate","selfLink":"https://localhost/mgmt/shared/iapp/package-management-tasks/66968651-2791-4e3d-9a7c-282981c36e1e"}

I have been using the default root/default credentials for the above calls, is that correct? I also tried with admin/admin with the same results.
What am I missing?
Any help to fix this issue is appreciated.

**Comment by npearce** [comment]
Hi @vishwanathj 
Sorry to hear you are having  you are running into problems. What version of BIG-IP are you installing this on? I've been testing against v13.1 and v14.

**Comment by vishwanathj** [comment]
Find below the output of the below command from the BIG IP instance

tmsh show /sys version

Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.0.2
  Build       0.0.6
  Edition     Point Release 2
  Date        Tue Jan 16 08:46:28 PST 2018

**Comment by vishwanathj** [comment]
What is the right username and password to be used? The default credentials when executing ssh are root/default. The default credentials to login to web GUI are admin/admin that I am aware of.
What log files and at which location should I be looking to further debug the issue?
Thanks in advance for all your help

**Comment by elv1s** [comment]
If you ssh into the mgmt ip do you get the prompt to change your password? I think this might be the problem?

You can check the logs at `/var/log/restjavad.0.log`

**Comment by vishwanathj** [comment]
I don't get a prompt to change the password. I have in the past continued to test other functionality using the root/default credentials

**Comment by npearce** [comment]
I'm using the admin account on my device running in AWS. And that's the same build I'm on. 

Based on the error - `java.lang.Exception: **Failed to read** /var/config/rest/downloads/BigStats-0.4.1-0009.noarch.rpm` - I'm wondering if the RPM was corrupted somehow during download or scp. 

Or, maybe its permission based: can you scp the file to the BIG-IP using the 'admin' account, too?
Did you set an 'admin' password on your device?

`tmsh modify auth user admin password <new pasword>` 

I just successfully created a new BIG-IP instance with the same RPM on:

```
# tmsh show sys ver

Sys::Version
Main Package
  Product     BIG-IP
  Version     13.1.0.2
  Build       0.0.6
  Edition     Point Release 2
  Date        Tue Jan 16 08:46:28 PST 2018
```

**Comment by npearce** [comment]
On my new BIG-IP:

```
# md5sum /var/config/rest/downloads/BigStats-0.4.1-0009.noarch.rpm 
6d14422c526e10363954c80fb0f86131  /var/config/rest/downloads/BigStats-0.4.1-0009.noarch.rpm
```

**Comment by elv1s** [comment]
@vishwanathj I followed your steps on a brand new instance and wasn't able to repro the issue. 

I also think you might have a corrupt file?

file on bigip
```
md5sum /var/config/rest/downloads/BigStats-0.4.1-0009.noarch.rpm 
6d14422c526e10363954c80fb0f86131  /var/config/rest/downloads/BigStats-0.4.1-0009.noarch.rpm
```

bigip version
```
Product: BIG-IP
Version: 13.1.0.7
Build: 0.0.1
Sequence: 13.1.0.7-0.0.1.0
BaseBuild: 0.0.1
Edition: Point Release 7
Date: Tue May 15 15:26:30 PDT 2018
Built: 180515152630
Changelist: 2557198
JobID: 1012030
```

**Comment by vishwanathj** [comment]
@npearce @elv1s Appreciate your response, I think the issue was related to corrupt file as the md5sum did not match with yours. I have now downloaded the rpm again and md5sum matches what you have. I am now able to successfully upload the package and see it listed as well

curl -u admin:admin -X GET http://localhost:8100/mgmt/shared/iapp/global-installed-packages
{"items":[{"id":"3616c231-6973-3608-8d74-1b87fc3d95e0","appName":"BigStats","packageName":"BigStats-0.4.1-0009.noarch","version":"0.4.1","release":"0009","arch":"noarch","tags":["IAPP"],"generation":1,"lastUpdateMicros":1541536592483156,"kind":"shared:iapp:global-installed-packages:installedpackagestate","selfLink":"https://localhost/mgmt/shared/iapp/global-installed-packages/3616c231-6973-3608-8d74-1b87fc3d95e0"}],"generation":1,"kind":"shared:iapp:global-installed-packages:installedpackagecollectionstate","lastUpdateMicros":1541536592483367,"selfLink":"https://localhost/mgmt/shared/iapp/global-installed-packages"}

**Comment by jmcalalang** [comment]
do you have a windows machine or something that might try to auto-open the package?

**Comment by npearce** [comment]
Great news, @vishwanathj 
I will start shipping an md5sum with the rpm's in future.
